version: '3.8'

services:
  appium:
    image: appium/appium:2.0.1
    ports:
      - "4723:4723"
    environment:
      - APPIUM_LOG_LEVEL=info
    networks:
      - swag-labs-net

  android-emulator:
    image: katalonstudio/android-emulator:30.0.26
    privileged: true
    ports:
      - "5554:5554"
      - "5555:5555"
    environment:
      - DEVICE=Pixel_4
      - ANDROID_AVD_HOME=/root/.android/avd
    volumes:
      - emulator-data:/root/.android
    networks:
      - swag-labs-net

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - appium
      - android-emulator
    volumes:
      - ./target:/app/target
    environment:
      - APPIUM_HOST=appium
      - APPIUM_PORT=4723
      - ANDROID_DEVICE=android-emulator:5554
    networks:
      - swag-labs-net

volumes:
  emulator-data:

networks:
  swag-labs-net:
    driver: bridge