name: Android Appium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  android-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Java (Maven requires JDK)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      # Install Node.js (needed for Appium)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Install Appium + UiAutomator2 driver
      - name: Install Appium
        run: |
          npm install -g appium@latest
          appium driver install uiautomator2
          appium -v

      # Run emulator, wait for boot, install app, run tests
      - name: Run Emulator + Appium + Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          profile: Nexus 6
          emulator-options: -no-window -no-audio -no-boot-anim
          script: |
            # Start Appium server in background
            appium --base-path /wd/hub --log-level info &
            sleep 5

            # Wait for emulator to boot completely
            adb wait-for-device
            boot_completed=""
            while [ -z "$boot_completed" ]; do
              boot_completed=$(adb -e shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
              echo "Waiting for emulator to boot..."
              sleep 5
            done
            echo "✅ Emulator booted!"

            # Unlock screen
            adb shell input keyevent 82

            # Install test app
            adb install -r ./apps/Android.SauceLabs.Mobile.Sample.app.2.7.1.apk

            # Run Maven tests
            mvn clean test

      # Cache Maven deps for faster builds
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
