name: Swag Labs Automation CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx for faster builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker compose --version

      # Start Docker containers (Appium, emulator, tests)
      - name: Start Docker containers
        run: |
          docker compose up --build -d
          # Wait for emulator to be ready (adjust timeout if needed)
          sleep 60

      # Run tests
      - name: Run tests
        run: |
          docker compose exec -T tests mvn test

      # Collect and upload test results
      - name: Upload TestNG reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: testng-reports
          path: target/surefire-reports/
          retention-days: 7

      # Stop and clean up containers
      - name: Stop Docker containers
        if: always()
        run: |
          docker compose down