name: Android Appium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  android-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Java (Maven requires JDK)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      # Install Node.js (needed for Appium)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.16.0'

      # Install Appium + UiAutomator2 driver
      - name: Install Appium
        run: |
          npm install -g appium@latest
          appium driver install uiautomator2
          appium -v

      # Start emulator
      - name: Start Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          profile: Nexus 6
          emulator-options: -no-window -no-audio -no-boot-anim
          script: echo "Emulator started"

      # Wait for emulator boot
      - name: Wait for Emulator
        run: |
          adb wait-for-device
          boot_completed=""
          while [ -z "$boot_completed" ] || [ "$boot_completed" != "1" ]; do
            boot_completed=$(adb -e shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
            echo "Waiting for emulator to boot..."
            sleep 5
          done
          echo "✅ Emulator booted!"
          adb shell input keyevent 82

      # Install test app
      - name: Install Test App
        run: adb install -r ./apps/Android.SauceLabs.Mobile.Sample.app.2.7.1.apk


      # Start Appium server
      - name: Start Appium
        run: |
          nohup appium --base-path /wd/hub --log-level info > appium.log 2>&1 &
          sleep 5

      # Run Maven tests
      - name: Run Maven Tests
        run: mvn clean test

      # Cache Maven deps for faster builds
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
